====================
Monday, June 2, 2014
====================


OperationalError: (2006, 'MySQL server has gone away')
------------------------------------------------------

I had the above error message caused by :manage:`watch_tim` since the
upgrade in Eupen. This had to do with the fact that I upgraded Django
from 1.5 to 1.6 at the same time. It was a side effect of an
optimization in Django 1.6 which Aymeric Augustin explains very well
in `Ticket 21597 <https://code.djangoproject.com/ticket/21597>`_. And
his recommended solution ("close the connection with ``from django.db
import connection; connection.close()`` when you know that your
program is going to be idle for a long time") was exactly the solution
for our case.

While looking for an explanation to this problem, I had some more
fiddling with :class:`lino.utils.ajax.AjaxExceptionResponse`.  There
was the following message in system log::

    201406-02 09:18:28 WARNING ajax : AjaxExceptionResponse:
    AttributeError
    'NoneType' object has no attribute 'parse_params'

This was of course not enough.  On a production server with
:setting:`DEBUG` False, we don't send the traceback to the client, but
we must at least send them to the logger then.  The above problem did
not yet reoccur until now, and as long as nobody complains, I'll just
let this wait.


Added Spanish language
----------------------

I addded Spanish to the list of maintained languages for 
Lino and :ref:`cosi`.
